use Mix.Config

# Configure your database
config :jeopardy, Jeopardy.Repo,
  username: "postgres",
  password: "postgres",
  database: "jeopardy_dev",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :jeopardy, JeopardyWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  # catch_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/webpack/bin/webpack.js",
      "--mode",
      "development",
      "--watch-stdin",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :jeopardy, JeopardyWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/jeopardy_web/(live|views)/.*(ex)$",
      ~r"lib/jeopardy_web/templates/.*(eex)$"
    ]
  ]

config :goth, json: {:system, "GCP_CREDENTIALS"}

config :jeopardy, Jeopardy.BIReplication,
  # 1 year, aka infinite
  frequency: 365 * 24 * 60 * 60 * 1000,
  bucket: "jeopardy_ryoung_test"

# milliseconds
config :jeopardy, early_buzz_penalty: 4_000

# Do not include metadata nor timestamps in development logs
# , level: :info
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

if File.exists?("config/dev.secret.exs"), do: import_config("dev.secret.exs")
