import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :jeopardy, JeopardyWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Jeopardy.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

config :logger,
  level: :info,
  backends: [:console, LogflareLogger.HttpBackend]

config :logflare_logger_backend,
  url: "https://api.logflare.app",
  level: :info,
  flush_interval: 1_000,
  max_batch_size: 50,
  metadata: :all

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
