name: test

on:
  project_card:
    types: [opened, moved]
    
jobs:
  notify-deploy:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        with:
          args: pubsub topics publish deploys --message="${{github.actor}}"
